### ISSUE TITLE
use cbor or protobuf for framer 

### ISSUE THREAD

**Issue by samyfodil** [taubyte/p2p#7]

**Comment by gedw99** [comment]
The framer needs to support Schema Evolution ?

**Comment by taubyte0** [comment]
@gedw99 yes. but did it in a more optimized way. check PR #13 
Closing this Issue.

**Comment by gedw99** [comment]
ok cbor.. I am using iceberg. https://iceberg.apache.org/docs/latest/evolution/

its a bit different approach from cobra or protobuf, etc in that its does not change the data, but instead the manifest.

**Comment by samyfodil** [comment]
is there a good golang package that can be used
does it support languages like rust, c/c++, js, python?

**Comment by gedw99** [comment]
Every language because it’s part of Apache arrow.

the golang code is still quite New.
It a little hard to use still .

It’s eaY  to find on GitHub.

**Comment by samyfodil** [comment]
@gedw99 the under the hood libp2p will still use grpc and cbor. Would be interesting to see how much faster iceberg is. We can setup a benchmark if you're up to it

**Comment by gedw99** [comment]
https://github.com/zeroshade

**Comment by samyfodil** [comment]
[zeroshade](https://github.com/zeroshade) implementation is still experimental. Closing this as #13 get the job done for now.
